spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:13306/workshop_eda_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: workshop_eda_test
    password: workshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
      format-sql: true