spring:
  config:
    activate:
      on-profile: dev
    import:
      - "aws-secretsmanager:/secret/db/eda-ws-coffee"
  datasource:
    url: jdbc:mysql://${host}:${port}/workshop_eda?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: true

